export const PRODUCT_GALLERY_IMAGE_STATE_ADD = 'PRODUCT_GALLERY_IMAGE_STATE_ADD';
export const PRODUCT_GALLERY_IMAGE_STATE_REMOVE = 'PRODUCT_GALLERY_IMAGE_STATE_REMOVE';

export const PRODUCT_TAGS_ASSIGN_ASSIGNING = 'PRODUCT_TAGS_ASSIGN_ASSIGNING';
export const PRODUCT_TAGS_ASSIGN_ASSIGNED = 'PRODUCT_TAGS_ASSIGN_ASSIGNED';
export const PRODUCT_TAGS_ASSIGN_FAILED = 'PRODUCT_TAGS_ASSIGN_FAILED';