export const GET_PRODUCTS_FETCHING = 'GET_PRODUCTS_FETCHING';
export const GET_PRODUCTS_RECEIVED = 'GET_PRODUCTS_RECEIVED';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const UPDATING_PRODUCT_FETCHING = 'UPDATING_PRODUCT_FETCHING';
export const UPDATING_PRODUCT_RECEIVED = 'UPDATING_PRODUCT_RECEIVED';
export const UPDATING_PRODUCT_FAILED = 'UPDATING_PRODUCT_FAILED';