export const GET_PRODUCTS_FETCHING = 'GET_PRODUCTS_FETCHING';
export const GET_PRODUCTS_RECEIVED = 'GET_PRODUCTS_RECEIVED';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const UPDATING_PRODUCT_FETCHING = 'UPDATING_PRODUCT_FETCHING';
export const UPDATING_PRODUCT_RECEIVED = 'UPDATING_PRODUCT_RECEIVED';
export const UPDATING_PRODUCT_FAILED = 'UPDATING_PRODUCT_FAILED';

export const UPDATE_PRODUCT_FILTER_CATEGORY = 'UPDATE_PRODUCT_FILTER_CATEGORY';
export const UPDATE_PRODUCT_FILTER_SEARCH = 'UPDATE_PRODUCT_FILTER_SEARCH';
export const UPDATE_PRODUCT_FILTER_ORDER = 'UPDATE_PRODUCT_FILTER_ORDER';

export const GET_PRODUCT_CATEGORIES_FETCHING = 'GET_PRODUCT_CATEGORIES_FETCHING';
export const GET_PRODUCT_CATEGORIES_RECEIVED = 'GET_PRODUCT_CATEGORIES_RECEIVED';
export const GET_PRODUCT_CATEGORIES_FAILED = 'GET_PRODUCT_CATEGORIES_FAILED';

export const GET_PRODUCT_FETCHING = 'GET_PRODUCT_FETCHING';
export const GET_PRODUCT_RECEIVED = 'GET_PRODUCT_RECEIVED';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const CREATE_PRODUCT_FETCHING ='CREATE_PRODUCT_FETCHING';
export const CREATE_PRODUCT_RECEIVED = 'CREATE_PRODUCT_RECEIVED';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';

export const PRODUCT_FIELD_CHANGED = 'PRODUCT_FIELD_CHANGED';
export const PRODUCT_SECTION_VALIDATION = 'PRODUCT_SECTION_VALIDATION';