export const ADD_PRODUCT_TAG_SAVING = 'ADD_PRODUCT_TAG_SAVING';
export const ADD_PRODUCT_TAG_SAVED = 'ADD_PRODUCT_TAG_SAVED';
export const ADD_PRODUCT_TAG_FAILED = 'ADD_PRODUCT_TAG_FAILED';

export const REMOVE_PRODUCT_TAG_SAVING = 'REMOVE_PRODUCT_TAG_SAVING';
export const REMOVE_PRODUCT_TAG_SAVED = 'REMOVE_PRODUCT_TAG_SAVED';
export const REMOVE_PRODUCT_TAG_FAILED = 'REMOVE_PRODUCT_TAG_FAILED';

export const GET_PRODUCT_TAGS_FETCHING = 'GET_PRODUCT_TAGS_FETCHING';
export const GET_PRODUCT_TAGS_RECEIVED = 'GET_PRODUCT_TAGS_RECEIVED';
export const GET_PRODUCT_TAGS_FAILED = 'GET_PRODUCT_TAGS_FAILED';

export const PRODUCT_TAGS_ASSIGN_ASSIGNING = 'PRODUCT_TAGS_ASSIGN_ASSIGNING';
export const PRODUCT_TAGS_ASSIGN_ASSIGNED = 'PRODUCT_TAGS_ASSIGN_ASSIGNED';
export const PRODUCT_TAGS_ASSIGN_FAILED = 'PRODUCT_TAGS_ASSIGN_FAILED';